apiVersion: kuadrant.io/v1beta2
kind: AuthPolicy
metadata:
  creationTimestamp: null
  name: petstorev2
spec:
  rules: {}
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: petstorev2
