openapi: "3.0.3"
info:
  title: "Pet Store API"
  version: "1.0.0"
x-kuadrant:
  route:
    name: "petstore"
    hostnames:
      - petstore.io
    parentRefs:
      - name: external
        namespace: gateway-system
paths:
  /v1/cat:
    get:
      operationId: "getCat"
      responses:
        405:
          description: "invalid input"
    post:
      operationId: "postCat"
      responses:
        405:
          description: "invalid input"
    x-kuadrant: ## Operation level Kuadrant Extension
      backendRefs:
        - name: petstore
          port: 80
          namespace: petstore
  /v1/dog:
    get:
      operationId: "getDog"
      responses:
        405:
          description: "invalid input"
    post:
      operationId: "postDog"
      responses:
        405:
          description: "invalid input"
    x-kuadrant: ## Operation level Kuadrant Extension
      backendRefs:
        - name: petstore
          port: 80
          namespace: petstore