apiVersion: kuadrant.io/v1beta2
kind: AuthPolicy
metadata:
  creationTimestamp: null
  name: petstore
spec:
  routeSelectors:
  - matches:
    - method: GET
      path:
        type: Exact
        value: /v1/snake
  - matches:
    - method: POST
      path:
        type: Exact
        value: /v1/cat
  - matches:
    - method: GET
      path:
        type: Exact
        value: /v1/dog
  rules:
    authentication:
      getDog_oidc:
        credentials: {}
        jwt:
          issuerUrl: https://example.com/.well-known/openid-configuration
        routeSelectors:
        - matches:
          - method: GET
            path:
              type: Exact
              value: /v1/dog
      getSnake_oidc:
        credentials: {}
        jwt:
          issuerUrl: https://example.com/.well-known/openid-configuration
        routeSelectors:
        - matches:
          - method: GET
            path:
              type: Exact
              value: /v1/snake
      getSnake_snakes_api_key:
        apiKey:
          selector:
            matchLabels:
              kuadrant.io/apikeys-by: snakes_api_key
        credentials:
          queryString:
            name: snake_token
        routeSelectors:
        - matches:
          - method: GET
            path:
              type: Exact
              value: /v1/snake
      postCat_cat_api_key:
        apiKey:
          selector:
            matchLabels:
              kuadrant.io/apikeys-by: cat_api_key
        credentials:
          customHeader:
            name: api_key
        routeSelectors:
        - matches:
          - method: POST
            path:
              type: Exact
              value: /v1/cat
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: petstore
status: {}

